### ISSUE TITLE
Selective search data not found at: /sequoia/data2/vavo/wsod/CASD/data/selective_search_data/voc_2007_trainval.mat

### ISSUE THREAD

**Issue by huyvvo** [DeLightCMU/CASD#15]
Hi, thank you for your interesting work.

I tried to set up the code for running. I downloaded the selective search data from the provided link and put them in data/selective_search_data but ran into this error:

```
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 109, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/trainval_net.py", line 74, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/trainval_net.py", line 74, in <listcomp>
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/trainval_net.py", line 71, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/sequoia/data2/vavo/wsod/CASD/tools/../lib/model/train_val.py", line 331, in get_training_roidb
    imdb.append_flipped_images()
  File "/sequoia/data2/vavo/wsod/CASD/tools/../lib/datasets/imdb.py", line 113, in append_flipped_images
    boxes = self.roidb[i]['boxes'].copy()
  File "/sequoia/data2/vavo/wsod/CASD/tools/../lib/datasets/imdb.py", line 74, in roidb
    self._roidb = self.roidb_handler()
  File "/sequoia/data2/vavo/wsod/CASD/tools/../lib/datasets/pascal_voc.py", line 142, in selective_search_roidb
    ss_roidb = self._load_selective_search_roidb(gt_roidb)
  File "/sequoia/data2/vavo/wsod/CASD/tools/../lib/datasets/pascal_voc.py", line 176, in _load_selective_search_roidb
    'Selective search data not found at: {}'.format(filename)
AssertionError: Selective search data not found at: /sequoia/data2/vavo/wsod/CASD/data/selective_search_data/voc_2007_trainval.mat
```
Do we need to transform the .pkl files to .mat files? Can you provide the code for the transformation please?

**Comment by huyvvo** [comment]
Or should the download link for selective search data be 
[https://dl.dropboxusercontent.com/s/orrt7o6bp6ae0tc/selective_search_data.tgz](https://dl.dropboxusercontent.com/s/orrt7o6bp6ae0tc/selective_search_data.tgz)
provided in [MELM](https://github.com/vasgaowei/pytorch_MELM) project?

**Comment by Justinhzy** [comment]
Hi,
you may find the mat file here(https://github.com/vasgaowei/pytorch_MELM).

**Comment by huyvvo** [comment]
Thank you!
